unit TestUDataModulo;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, Classes, UDataModulo, DB, DBClient, Forms, SysUtils;

type
  // Test methods for class TDataModulo

  TestTDataModulo = class(TTestCase)
  strict private
    FDataModulo: TDataModulo;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestCalcTotalItens;
    procedure TestCalcTotalGeral;
  end;

implementation

procedure TestTDataModulo.SetUp;
begin
  FDataModulo := TDataModulo.Create(nil);
end;

procedure TestTDataModulo.TearDown;
begin
  FDataModulo.Free;
  FDataModulo := nil;
end;

procedure TestTDataModulo.TestCalcTotalItens;
var
  ReturnValue: Currency;
  Valor2: Currency;
  Valor1: Currency;
begin
  Valor2:= 2;
  Valor1:= 3;

  ReturnValue := FDataModulo.CalcTotalItens(Valor1, Valor2);
  CheckEquals(6, ReturnValue, 'A função CalcTotalItens falhou!')
end;

procedure TestTDataModulo.TestCalcTotalGeral;
var
  ReturnValue: Currency;
  Valor2: Currency;
  Valor1: Currency;
begin
  Valor2:= 2;
  Valor1:= 3;

  ReturnValue := FDataModulo.CalcTotalGeral(Valor1, Valor2);
  CheckEquals(5, ReturnValue, 'A função CalcTotalGeral falhou!')
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTDataModulo.Suite);
end.

